== Migration notes (6 septembre 2023 à 15:14:10 CEST)

=== Updates

* `bonita.runtime.version` has been updated from `7.15.0` to `8.0.0`.
* `bonita-project-maven-plugin.version` has been updated from `0.0.6` to `0.1.1`.
* `com.company.model:bdm-client:jar:1.0.0` dependency has been replaced with `${project.groupId}:procurement-example-bdm-model:jar:${project.version}`.
* The project layout has been changed in favor of a multi modules maven project. It means that files location inside the project have changed.  It is a technical change and will not impact the design usage in Bonita Studio.New maven modules and their respective `pom.xml` files are *reserved for internal Studio use*.
* Project's Business Data Model is now build in its own maven module. While it does not impact the design usage, it can now be built and deployed independently from a Studio.  The BDM model dependency share the same `version` and `groupId` of the parent project. It is enforced by the format of the Bonita project and must not be changed.

== Migration notes (October 6, 2022 at 3:15:37 PM CEST)

=== Updates

* `bonita.runtime.version` has been updated from `7.13.0` to `7.15.0`.
* `bonita-project-maven-plugin.version` has been updated from `0.0.3` to `0.0.6`.

== Migration notes (28 novembre 2021 à 19:07:29 CET)

=== Updates

* `bonita-project-maven-plugin.version` has been updated from `0.0.1` to `0.0.3`.

== Migration notes (July 23, 2021 at 11:09:09 AM CEST)

=== Additions

* Bonita projects are now Maven projects and rely on the https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html[Maven dependency mechanism] to manage their dependencies. Check the documentation for more information about https://www.bonitasoft.com/bos_redirect.php?bos_redirect_id=727&bos_redirect_major_version=7.13&bos_redirect_minor_version=0&bos_redirect_product=bos[Project composition].

=== Updates

* Groovy version has been updated from `2.4.x` to `3.0.x`
* Only Java `11` version is now supported. This might impact your existing projet if you were still using Java 8. Some dependencies in your project might be incompatible with the _Java Platform Module System_ introduced in Java 9.
* procurement application theme has been updated to Bonita default theme.
* procurement application layout has been updated to Bonita default layout.

=== Removals

* `lib` folder and its content has been removed.

