<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.bonitasoft.example</groupId>
    <artifactId>procurement-example-parent</artifactId>
    <version>3.2</version>
  </parent>
  <artifactId>procurement-example</artifactId>
  <name>procurement-example</name>
  <description>Official Procurement Living Application example for Bonita</description>
  <dependencies>
    <dependency>
      <groupId>com.bonitasoft.engine</groupId>
      <artifactId>bonita-common-sp</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-json</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-xml</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-nio</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-datetime</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-dateutil</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-sql</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-templates</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-jsr223</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-jmx</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-yaml</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-servlet</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.bonitasoft.actorfilter</groupId>
      <artifactId>bonita-actorfilter-initiator</artifactId>
      <version>1.0.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.bonitasoft.connectors</groupId>
      <artifactId>bonita-connector-rest</artifactId>
      <version>1.2.0</version>
    </dependency>
    <dependency>
      <groupId>org.bonitasoft.connectors</groupId>
      <artifactId>bonita-connector-document-converter</artifactId>
      <version>2.3.0</version>
    </dependency>
    <dependency>
      <groupId>org.bonitasoft.connectors</groupId>
      <artifactId>bonita-connector-document-templating</artifactId>
      <version>2.3.0</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>procurement-example-bdm-model</artifactId>
      <version>${project.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.bonitasoft.web.application</groupId>
      <artifactId>bonita-admin-application-sp</artifactId>
      <type>zip</type>
      <classifier>application</classifier>
      <scope>compile</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <artifactId>gmavenplus-plugin</artifactId>
        <groupId>org.codehaus.gmavenplus</groupId>
        <executions>
          <execution>
            <id>bonita-project-properties</id>
            <goals>
              <goal>execute</goal>
            </goals>
          </execution>
          <execution>
            <id>generate-application-properties</id>
            <goals>
              <goal>execute</goal>
            </goals>
          </execution>
          <execution>
            <id>generate-classpath-assembly</id>
            <goals>
              <goal>execute</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>bonita-project-maven-plugin</artifactId>
        <groupId>org.bonitasoft.maven</groupId>
        <executions>
          <execution>
            <id>process-bonita-artifacts</id>
            <goals>
              <goal>copy-provided-pages</goal>
              <goal>business-archive</goal>
              <goal>uid-page</goal>
              <goal>merge-configuration</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>build-helper-maven-plugin</artifactId>
        <groupId>org.codehaus.mojo</groupId>
        <executions>
          <execution>
            <id>add-source-folder</id>
            <goals>
              <goal>add-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>src-groovy</source>
                <source>${project.build.directory}/generated-groovy-sources</source>
              </sources>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <executions>
          <execution>
            <id>application-archive</id>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
          <execution>
            <id>application-classpath</id>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>bundle</id>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-dependency-plugin</artifactId>
            <executions>
              <execution>
                <id>prepare-bundle-enterprise</id>
                <goals>
                  <goal>unpack</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.codehaus.gmavenplus</groupId>
            <artifactId>gmavenplus-plugin</artifactId>
            <executions>
              <execution>
                <id>configure-bundle</id>
                <goals>
                  <goal>execute</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <artifactId>maven-assembly-plugin</artifactId>
            <executions>
              <execution>
                <id>bundle-archive-enterprise</id>
                <goals>
                  <goal>single</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>docker</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.codehaus.gmavenplus</groupId>
            <artifactId>gmavenplus-plugin</artifactId>
            <executions>
              <execution>
                <id>generate-docker-resources</id>
                <goals>
                  <goal>execute</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>build-image</id>
                <goals>
                  <goal>exec</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
      <properties>
        <docker.baseImageRepository>bonitasoft.jfrog.io/docker/bonita-subscription</docker.baseImageRepository>
      </properties>
    </profile>
  </profiles>
</project>
