<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:definition="http://www.bonitasoft.org/ns/connector/definition/6.1" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:parameter="http://www.bonitasoft.org/ns/studio/parameter" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_yBZV0BKsEeWPr7pxbi20Rg" name="Procurement request" author="bonitasoft" bonitaVersion="7.13.0" bonitaModelVersion="7.12.0-004" configId="ACED000574000E372E392E302D303032372E392E33">
    <elements xmi:type="process:Pool" xmi:id="_yBZV0RKsEeWPr7pxbi20Rg" documentation="Process for a procurement request" name="Procurement request">
      <elements xmi:type="process:Lane" xmi:id="_yBZ84BKsEeWPr7pxbi20Rg" name="Requestor" actor="_yBZ9gxKsEeWPr7pxbi20Rg">
        <elements xmi:type="process:StartEvent" xmi:id="_yBZ84RKsEeWPr7pxbi20Rg" name="Specify need &amp; identify suitable suppliers" outgoing="_el_woNofEem3nK4z4KeV0A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_yBZ84xKsEeWPr7pxbi20Rg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_yBZ85BKsEeWPr7pxbi20Rg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_yBZ85RKsEeWPr7pxbi20Rg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_yBZ85hKsEeWPr7pxbi20Rg" name="Review quotations &amp; select supplier" outgoing="_yBZ9fRKsEeWPr7pxbi20Rg" incoming="_GwyxgBK3EeWPr7pxbi20Rg" overrideActorsOfTheLane="false">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_8upM8NokEem3nK4z4KeV0A" source="_8umwsNokEem3nK4z4KeV0A"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_j3E64T79EeeFUpJtjfPkKQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_j3E64j79EeeFUpJtjfPkKQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_j3E64z79EeeFUpJtjfPkKQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_yBZ88BKsEeWPr7pxbi20Rg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_j3E7Aj79EeeFUpJtjfPkKQ" name="request" content="request" type="TYPE_VARIABLE" returnType="com.company.model.Request">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_OrnRTdoXEem3nK4z4KeV0A" name="request" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Request"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_j3E7BD79EeeFUpJtjfPkKQ" name="getSelectedSupplier" content="if (selectedSupplierId == null) {&#xD;&#xA;&#x9;return null&#xD;&#xA;} else {&#xD;&#xA;&#x9;return supplierDAO.findById(Long.valueOf(selectedSupplierId))&#xD;&#xA;}" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Supplier">
              <referencedElements xmi:type="expression:Expression" xmi:id="_ll6E4NomEem3nK4z4KeV0A" name="supplierDAO" content="supplierDAO" type="TYPE_BUSINESS_OBJECT_DAO" returnType="com.company.model.SupplierDAO" returnTypeFixed="true"/>
              <referencedElements xmi:type="process:ContractInput" xmi:id="_ll6E4domEem3nK4z4KeV0A" name="selectedSupplierId" description="Id of the supplier selected for procurement">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_ll6E4tomEem3nK4z4KeV0A"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_yBZ89xKsEeWPr7pxbi20Rg" type="JAVA_METHOD" expression="setSelectedSupplier">
              <inputTypes>com.company.model.Supplier</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_XV61gD7_EeeFUpJtjfPkKQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_XV61gT7_EeeFUpJtjfPkKQ" name="request" content="request" type="TYPE_VARIABLE" returnType="com.company.model.Request">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Orn4RNoXEem3nK4z4KeV0A" name="request" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Request"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_XV61gj7_EeeFUpJtjfPkKQ" name="getCurrentDate" content="java.time.LocalDate.now()" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate"/>
            <operator xmi:type="expression:Operator" xmi:id="_XV61gz7_EeeFUpJtjfPkKQ" type="JAVA_METHOD" expression="setCompletionDate">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_j3E65j79EeeFUpJtjfPkKQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_j3E65z79EeeFUpJtjfPkKQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_j3E66D79EeeFUpJtjfPkKQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_j3E66T79EeeFUpJtjfPkKQ" name="multiInstanceIterator" content="quotation" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_j3E66j79EeeFUpJtjfPkKQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_yBZ9BBKsEeWPr7pxbi20Rg">
            <targetForm xmi:type="expression:Expression" xmi:id="_j3FiED79EeeFUpJtjfPkKQ" name="procurementReviewQuotationsForm" content="d5c2669f-f688-43e6-ace9-dc475ed6833c" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_yBZ9BhKsEeWPr7pxbi20Rg">
            <inputs xmi:type="process:ContractInput" xmi:id="_j3FiFD79EeeFUpJtjfPkKQ" name="selectedSupplierId" description="Id of the supplier selected for procurement">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_j3FiFT79EeeFUpJtjfPkKQ"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_j3E67z79EeeFUpJtjfPkKQ" name="3600000" content="3600000" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_yBZ9CRKsEeWPr7pxbi20Rg" name="Update request after supplier selected" outgoing="_yBZ9gBKsEeWPr7pxbi20Rg" incoming="_fEY4QBK3EeWPr7pxbi20Rg">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_KO5F4NolEem3nK4z4KeV0A" source="_KO1bgNolEem3nK4z4KeV0A"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_j3FiIz79EeeFUpJtjfPkKQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_j3FiJD79EeeFUpJtjfPkKQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_j3FiJT79EeeFUpJtjfPkKQ" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_UaHM8FEpEeyRA_m9wzMnTg" name="generateQuotationRequestWord" definitionId="document-templating" event="ON_ENTER" ignoreErrors="true" definitionVersion="1.0.1">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_UaHM8VEpEeyRA_m9wzMnTg" definitionId="document-templating" version="1.0.1" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_UaHM8lEpEeyRA_m9wzMnTg" key="documentInput">
                <expression xmi:type="expression:Expression" xmi:id="_UaHM81EpEeyRA_m9wzMnTg" name="quoteRequestTemplate" content="quoteRequestTemplate" type="DOCUMENT_REF_TYPE" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Document" xmi:id="_UaHM9FEpEeyRA_m9wzMnTg" name="quoteRequestTemplate"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_UaHM9VEpEeyRA_m9wzMnTg" key="replacements">
                <expression xmi:type="expression:TableExpression" xmi:id="_UaHM9lEpEeyRA_m9wzMnTg">
                  <expressions xmi:type="expression:ListExpression" xmi:id="_UaHM91EpEeyRA_m9wzMnTg">
                    <expressions xmi:type="expression:Expression" xmi:id="_UaHM-FEpEeyRA_m9wzMnTg" name="supplier" content="supplier" returnTypeFixed="true"/>
                    <expressions xmi:type="expression:Expression" xmi:id="_UaHM-VEpEeyRA_m9wzMnTg" name="getSupplier" content="request.selectedSupplier" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Supplier">
                      <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_UaHM-lEpEeyRA_m9wzMnTg" name="request" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Request"/>
                    </expressions>
                  </expressions>
                  <expressions xmi:type="expression:ListExpression" xmi:id="_UaHM-1EpEeyRA_m9wzMnTg">
                    <expressions xmi:type="expression:Expression" xmi:id="_UaHM_FEpEeyRA_m9wzMnTg" name="requestdate" content="requestdate" returnTypeFixed="true"/>
                    <expressions xmi:type="expression:Expression" xmi:id="_UaHM_VEpEeyRA_m9wzMnTg" name="formatDateToday" content="import java.time.format.DateTimeFormatter;&#xD;&#xA;DateTimeFormatter dtf = DateTimeFormatter.ofPattern(&quot;yyyy/MM/dd&quot;)&#xD;&#xA;return request.creationDate.format(dtf)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                      <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_UaHM_lEpEeyRA_m9wzMnTg" name="request" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Request"/>
                    </expressions>
                  </expressions>
                  <expressions xmi:type="expression:ListExpression" xmi:id="_UaHM_1EpEeyRA_m9wzMnTg">
                    <expressions xmi:type="expression:Expression" xmi:id="_UaHNAFEpEeyRA_m9wzMnTg" name="requestId" content="requestId" returnTypeFixed="true"/>
                    <expressions xmi:type="expression:Expression" xmi:id="_UaHNAVEpEeyRA_m9wzMnTg" name="getCaseId" content="request.caseId" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                      <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_UaHNAlEpEeyRA_m9wzMnTg" name="request" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Request"/>
                    </expressions>
                  </expressions>
                  <expressions xmi:type="expression:ListExpression" xmi:id="_UaHNA1EpEeyRA_m9wzMnTg">
                    <expressions xmi:type="expression:Expression" xmi:id="_UaHNBFEpEeyRA_m9wzMnTg" name="requestSummary" content="requestSummary" returnTypeFixed="true"/>
                    <expressions xmi:type="expression:Expression" xmi:id="_UaHNBVEpEeyRA_m9wzMnTg" name="getSummary" content="request.summary" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                      <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_UaHNBlEpEeyRA_m9wzMnTg" name="request" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Request"/>
                    </expressions>
                  </expressions>
                  <expressions xmi:type="expression:ListExpression" xmi:id="_UaHNB1EpEeyRA_m9wzMnTg">
                    <expressions xmi:type="expression:Expression" xmi:id="_UaHNCFEpEeyRA_m9wzMnTg" name="requestDescription" content="requestDescription" returnTypeFixed="true"/>
                    <expressions xmi:type="expression:Expression" xmi:id="_UaHNCVEpEeyRA_m9wzMnTg" name="getDescription" content="request.description" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                      <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_UaHNClEpEeyRA_m9wzMnTg" name="request" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Request"/>
                    </expressions>
                  </expressions>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_UaHNC1EpEeyRA_m9wzMnTg" key="outputFileName">
                <expression xmi:type="expression:Expression" xmi:id="_UaHNDFEpEeyRA_m9wzMnTg" name="createQRName" content="&quot;Quotation_Request_&quot;+request.caseId+&quot;.docx&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_UaHNDVEpEeyRA_m9wzMnTg" name="request" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Request"/>
                </expression>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_UaHNDlEpEeyRA_m9wzMnTg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_UaHND1EpEeyRA_m9wzMnTg" name="quoteRequestWord" content="quoteRequestWord" type="DOCUMENT_REF_TYPE">
                <referencedElements xmi:type="process:Document" xmi:id="_UaHNEFEpEeyRA_m9wzMnTg" name="quoteRequestWord"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_UaHNEVEpEeyRA_m9wzMnTg" name="document" content="document" type="CONNECTOR_OUTPUT_TYPE" returnType="org.bonitasoft.engine.bpm.document.DocumentValue">
                <referencedElements xmi:type="definition:Output" xmi:id="_UaHNElEpEeyRA_m9wzMnTg" name="document" type="org.bonitasoft.engine.bpm.document.DocumentValue"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_UaHNE1EpEeyRA_m9wzMnTg" type="DOCUMENT_CREATE_UPDATE"/>
            </outputs>
          </connectors>
          <connectors xmi:type="process:Connector" xmi:id="_c97oIFEpEeyRA_m9wzMnTg" name="generatePDFFile" definitionId="document-converter" event="ON_ENTER" ignoreErrors="true" definitionVersion="1.0.2">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_c97oIVEpEeyRA_m9wzMnTg" definitionId="document-converter" version="1.0.2" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_c97oIlEpEeyRA_m9wzMnTg" key="sourceDocument">
                <expression xmi:type="expression:Expression" xmi:id="_c97oI1EpEeyRA_m9wzMnTg" name="quoteRequestWord" content="quoteRequestWord" type="DOCUMENT_REF_TYPE" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Document" xmi:id="_HhEhIFEtEeyRA_m9wzMnTg" name="quoteRequestWord"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_c97oJVEpEeyRA_m9wzMnTg" key="encoding">
                <expression xmi:type="expression:Expression" xmi:id="_c97oJlEpEeyRA_m9wzMnTg" name="windows-1252" content="windows-1252" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_c97oJ1EpEeyRA_m9wzMnTg" key="outputFileName">
                <expression xmi:type="expression:Expression" xmi:id="_c97oKFEpEeyRA_m9wzMnTg" name="setPdfFileName" content="return &quot;Quotation_Request_&quot;+ request.caseId +&quot;_final.pdf&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_c97oKVEpEeyRA_m9wzMnTg" name="request" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Request"/>
                </expression>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_c97oKlEpEeyRA_m9wzMnTg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_c97oK1EpEeyRA_m9wzMnTg" name="quoteRequestPDF" content="quoteRequestPDF" type="DOCUMENT_REF_TYPE">
                <referencedElements xmi:type="process:Document" xmi:id="_c97oLFEpEeyRA_m9wzMnTg" name="quoteRequestPDF"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_c97oLVEpEeyRA_m9wzMnTg" name="outputDocumentValue" content="outputDocumentValue" type="CONNECTOR_OUTPUT_TYPE" returnType="org.bonitasoft.engine.bpm.document.DocumentValue">
                <referencedElements xmi:type="definition:Output" xmi:id="_c97oLlEpEeyRA_m9wzMnTg" name="outputDocumentValue" type="org.bonitasoft.engine.bpm.document.DocumentValue"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_c97oL1EpEeyRA_m9wzMnTg" type="DOCUMENT_CREATE_UPDATE"/>
            </outputs>
          </connectors>
          <connectors xmi:type="process:Connector" xmi:id="_selSkFEpEeyRA_m9wzMnTg" documentation="It works for uploading documents smaller than 4MB only. For documents greater than 4MB, you need to use createUploadSession in your POST url" name="uploadWordFile" definitionId="rest-file-put" event="ON_FINISH" ignoreErrors="true" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_selSkVEpEeyRA_m9wzMnTg" definitionId="rest-file-put" version="1.0.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSklEpEeyRA_m9wzMnTg" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_selSk1EpEeyRA_m9wzMnTg" name="concatenateUploadURL" content="return 'https://graph.microsoft.com/v1.0/drives/'+ sharepointParentFolder + '/root:/Quote%20Requests/'+ sharepointCaseFolder + '/QuoteRequest-'+ request.caseId +'.docx:/content'" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_hjeJAF6UEeypT86PGIy9Ug" name="request" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Request"/>
                  <referencedElements xmi:type="process:Data" xmi:id="_hjeJAV6UEeypT86PGIy9Ug" documentation="the name of the folder created by the process" name="sharepointCaseFolder" dataType="_yBZ9nxKsEeWPr7pxbi20Rg"/>
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_hjeJAl6UEeypT86PGIy9Ug" name="sharepointParentFolder" typeClassname="java.lang.String" description="use this parameter to store the ID of the Sharepoint Drive that you need to use as part of the URL for your REST calls&#xD;&#xA;"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSllEpEeyRA_m9wzMnTg" key="contentType">
                <expression xmi:type="expression:Expression" xmi:id="_selSl1EpEeyRA_m9wzMnTg" name="application/octet-stream" content="application/octet-stream" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSmFEpEeyRA_m9wzMnTg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_selSmVEpEeyRA_m9wzMnTg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSmlEpEeyRA_m9wzMnTg" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_selSm1EpEeyRA_m9wzMnTg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSnFEpEeyRA_m9wzMnTg" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_selSnVEpEeyRA_m9wzMnTg">
                  <expressions xmi:type="expression:ListExpression" xmi:id="_selSnlEpEeyRA_m9wzMnTg">
                    <expressions xmi:type="expression:Expression" xmi:id="_selSn1EpEeyRA_m9wzMnTg" name="Authorization" content="Authorization"/>
                    <expressions xmi:type="expression:Expression" xmi:id="_selSoFEpEeyRA_m9wzMnTg" name="sharepointToken" content="sharepointToken" type="TYPE_VARIABLE">
                      <referencedElements xmi:type="process:Data" xmi:id="_selSoVEpEeyRA_m9wzMnTg" documentation="token generated by AzureAD that you need to use for all REST API calls&#xD;&#xA;" name="sharepointToken" dataType="_yBZ9nxKsEeWPr7pxbi20Rg"/>
                    </expressions>
                  </expressions>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSolEpEeyRA_m9wzMnTg" key="documentBody">
                <expression xmi:type="expression:Expression" xmi:id="_selSo1EpEeyRA_m9wzMnTg" name="quoteRequestWord" content="quoteRequestWord" type="DOCUMENT_REF_TYPE" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Document" xmi:id="_selSpFEpEeyRA_m9wzMnTg" name="quoteRequestWord"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSpVEpEeyRA_m9wzMnTg" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_selSplEpEeyRA_m9wzMnTg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSp1EpEeyRA_m9wzMnTg" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_selSqFEpEeyRA_m9wzMnTg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSqVEpEeyRA_m9wzMnTg" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_selSqlEpEeyRA_m9wzMnTg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSq1EpEeyRA_m9wzMnTg" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_selSrFEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSrVEpEeyRA_m9wzMnTg" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_selSrlEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSr1EpEeyRA_m9wzMnTg" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_selSsFEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSsVEpEeyRA_m9wzMnTg" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_selSslEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSs1EpEeyRA_m9wzMnTg" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_selStFEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selStVEpEeyRA_m9wzMnTg" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_selStlEpEeyRA_m9wzMnTg" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSt1EpEeyRA_m9wzMnTg" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_selSuFEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSuVEpEeyRA_m9wzMnTg" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_selSulEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSu1EpEeyRA_m9wzMnTg" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_selSvFEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSvVEpEeyRA_m9wzMnTg" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_selSvlEpEeyRA_m9wzMnTg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSv1EpEeyRA_m9wzMnTg" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_selSwFEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSwVEpEeyRA_m9wzMnTg" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_selSwlEpEeyRA_m9wzMnTg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSw1EpEeyRA_m9wzMnTg" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_selSxFEpEeyRA_m9wzMnTg" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSxVEpEeyRA_m9wzMnTg" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_selSxlEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSx1EpEeyRA_m9wzMnTg" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_selSyFEpEeyRA_m9wzMnTg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSyVEpEeyRA_m9wzMnTg" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_selSylEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSy1EpEeyRA_m9wzMnTg" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_selSzFEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSzVEpEeyRA_m9wzMnTg" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_selSzlEpEeyRA_m9wzMnTg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selSz1EpEeyRA_m9wzMnTg" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_selS0FEpEeyRA_m9wzMnTg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_selS0VEpEeyRA_m9wzMnTg" key="trust_strategy">
                <expression xmi:type="expression:Expression" xmi:id="_selS0lEpEeyRA_m9wzMnTg" name="DEFAULT" content="DEFAULT" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_selS01EpEeyRA_m9wzMnTg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_selS1FEpEeyRA_m9wzMnTg" name="sharepointWordUploadMessage" content="sharepointWordUploadMessage" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_selS1VEpEeyRA_m9wzMnTg" documentation="store the response message of the upload rest call&#xD;&#xA;" name="sharepointWordUploadMessage" dataType="_yBZ9nxKsEeWPr7pxbi20Rg"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_selS1lEpEeyRA_m9wzMnTg" name="status_message" content="status_message" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_selS11EpEeyRA_m9wzMnTg" name="status_message" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_selS2FEpEeyRA_m9wzMnTg" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <connectors xmi:type="process:Connector" xmi:id="_29KxUFEpEeyRA_m9wzMnTg" documentation="It works for uploading documents smaller than 4MB only. For documents greater than 4MB, you need to use createUploadSession in your POST url" name="uploadPDFFile" definitionId="rest-file-put" event="ON_FINISH" ignoreErrors="true" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_29KxUVEpEeyRA_m9wzMnTg" definitionId="rest-file-put" version="1.0.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29KxUlEpEeyRA_m9wzMnTg" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_29KxU1EpEeyRA_m9wzMnTg" name="concatenateUploadPDFURL" content="return 'https://graph.microsoft.com/v1.0/drives/'+ sharepointParentFolder +'/root:/Quote%20Requests/'+ sharepointCaseFolder + '/QuoteRequest-'+ request.caseId +'-final.pdf:/content'" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_nR0y8F6UEeypT86PGIy9Ug" name="request" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Request"/>
                  <referencedElements xmi:type="process:Data" xmi:id="_nR0y8V6UEeypT86PGIy9Ug" documentation="the name of the folder created by the process" name="sharepointCaseFolder" dataType="_yBZ9nxKsEeWPr7pxbi20Rg"/>
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_nR0y8l6UEeypT86PGIy9Ug" name="sharepointParentFolder" typeClassname="java.lang.String" description="use this parameter to store the ID of the Sharepoint Drive that you need to use as part of the URL for your REST calls&#xD;&#xA;"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29KxVlEpEeyRA_m9wzMnTg" key="contentType">
                <expression xmi:type="expression:Expression" xmi:id="_29KxV1EpEeyRA_m9wzMnTg" name="application/octet-stream" content="application/octet-stream" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29KxWFEpEeyRA_m9wzMnTg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_29KxWVEpEeyRA_m9wzMnTg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29KxWlEpEeyRA_m9wzMnTg" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_29KxW1EpEeyRA_m9wzMnTg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29KxXFEpEeyRA_m9wzMnTg" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_29KxXVEpEeyRA_m9wzMnTg">
                  <expressions xmi:type="expression:ListExpression" xmi:id="_29KxXlEpEeyRA_m9wzMnTg">
                    <expressions xmi:type="expression:Expression" xmi:id="_29KxX1EpEeyRA_m9wzMnTg" name="Authorization" content="Authorization"/>
                    <expressions xmi:type="expression:Expression" xmi:id="_29KxYFEpEeyRA_m9wzMnTg" name="sharepointToken" content="sharepointToken" type="TYPE_VARIABLE">
                      <referencedElements xmi:type="process:Data" xmi:id="_29KxYVEpEeyRA_m9wzMnTg" documentation="token generated by AzureAD that you need to use for all REST API calls&#xD;&#xA;" name="sharepointToken" dataType="_yBZ9nxKsEeWPr7pxbi20Rg"/>
                    </expressions>
                  </expressions>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29KxYlEpEeyRA_m9wzMnTg" key="documentBody">
                <expression xmi:type="expression:Expression" xmi:id="_29KxY1EpEeyRA_m9wzMnTg" name="quoteRequestPDF" content="quoteRequestPDF" type="DOCUMENT_REF_TYPE" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Document" xmi:id="_29KxZFEpEeyRA_m9wzMnTg" name="quoteRequestPDF"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29KxZVEpEeyRA_m9wzMnTg" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_29KxZlEpEeyRA_m9wzMnTg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29KxZ1EpEeyRA_m9wzMnTg" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_29KxaFEpEeyRA_m9wzMnTg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29KxaVEpEeyRA_m9wzMnTg" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_29KxalEpEeyRA_m9wzMnTg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29Kxa1EpEeyRA_m9wzMnTg" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_29KxbFEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29KxbVEpEeyRA_m9wzMnTg" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_29KxblEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29Kxb1EpEeyRA_m9wzMnTg" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_29KxcFEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29KxcVEpEeyRA_m9wzMnTg" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_29KxclEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29Kxc1EpEeyRA_m9wzMnTg" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_29KxdFEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29KxdVEpEeyRA_m9wzMnTg" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_29KxdlEpEeyRA_m9wzMnTg" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29Kxd1EpEeyRA_m9wzMnTg" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_29KxeFEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29KxeVEpEeyRA_m9wzMnTg" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_29KxelEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29Kxe1EpEeyRA_m9wzMnTg" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_29KxfFEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29KxfVEpEeyRA_m9wzMnTg" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_29KxflEpEeyRA_m9wzMnTg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29Kxf1EpEeyRA_m9wzMnTg" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_29KxgFEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29KxgVEpEeyRA_m9wzMnTg" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_29KxglEpEeyRA_m9wzMnTg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29Kxg1EpEeyRA_m9wzMnTg" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_29KxhFEpEeyRA_m9wzMnTg" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29KxhVEpEeyRA_m9wzMnTg" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_29KxhlEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29Kxh1EpEeyRA_m9wzMnTg" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_29KxiFEpEeyRA_m9wzMnTg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29KxiVEpEeyRA_m9wzMnTg" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_29KxilEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29Kxi1EpEeyRA_m9wzMnTg" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_29KxjFEpEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29KxjVEpEeyRA_m9wzMnTg" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_29KxjlEpEeyRA_m9wzMnTg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29Kxj1EpEeyRA_m9wzMnTg" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_29KxkFEpEeyRA_m9wzMnTg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_29KxkVEpEeyRA_m9wzMnTg" key="trust_strategy">
                <expression xmi:type="expression:Expression" xmi:id="_29KxklEpEeyRA_m9wzMnTg" name="DEFAULT" content="DEFAULT" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_29Kxk1EpEeyRA_m9wzMnTg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_29KxlFEpEeyRA_m9wzMnTg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_29KxlVEpEeyRA_m9wzMnTg" name="bodyAsString" content="bodyAsString" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_29KxllEpEeyRA_m9wzMnTg" name="bodyAsString" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_29Kxl1EpEeyRA_m9wzMnTg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_29KxmFEpEeyRA_m9wzMnTg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_29KxmVEpEeyRA_m9wzMnTg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_29KxmlEpEeyRA_m9wzMnTg" name="bodyAsObject" content="bodyAsObject" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Object">
                <referencedElements xmi:type="definition:Output" xmi:id="_29Kxm1EpEeyRA_m9wzMnTg" name="bodyAsObject" type="java.lang.Object"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_29KxnFEpEeyRA_m9wzMnTg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_29KxnVEpEeyRA_m9wzMnTg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_29KxnlEpEeyRA_m9wzMnTg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_29Kxn1EpEeyRA_m9wzMnTg" name="headers" content="headers" type="CONNECTOR_OUTPUT_TYPE" returnType="java.util.Map">
                <referencedElements xmi:type="definition:Output" xmi:id="_29KxoFEpEeyRA_m9wzMnTg" name="headers" type="java.util.Map"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_29KxoVEpEeyRA_m9wzMnTg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_29KxolEpEeyRA_m9wzMnTg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_29Kxo1EpEeyRA_m9wzMnTg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_29KxpFEpEeyRA_m9wzMnTg" name="status_code" content="status_code" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Integer">
                <referencedElements xmi:type="definition:Output" xmi:id="_29KxpVEpEeyRA_m9wzMnTg" name="status_code" type="java.lang.Integer"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_29KxplEpEeyRA_m9wzMnTg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_29Kxp1EpEeyRA_m9wzMnTg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_29KxqFEpEeyRA_m9wzMnTg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_29KxqVEpEeyRA_m9wzMnTg" name="status_message" content="status_message" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_29KxqlEpEeyRA_m9wzMnTg" name="status_message" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_29Kxq1EpEeyRA_m9wzMnTg" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <operations xmi:type="expression:Operation" xmi:id="_j3FiJj79EeeFUpJtjfPkKQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_j3FiJz79EeeFUpJtjfPkKQ" name="request" content="request" type="TYPE_VARIABLE" returnType="com.company.model.Request">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_OrofatoXEem3nK4z4KeV0A" name="request" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Request"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_j3FiKT79EeeFUpJtjfPkKQ" name="Completed" content="Completed"/>
            <operator xmi:type="expression:Operator" xmi:id="_j3FiKj79EeeFUpJtjfPkKQ" type="JAVA_METHOD" expression="setStatus">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_j3FiKz79EeeFUpJtjfPkKQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_j3FiLD79EeeFUpJtjfPkKQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_j3FiLT79EeeFUpJtjfPkKQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_j3FiLj79EeeFUpJtjfPkKQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_j3FiLz79EeeFUpJtjfPkKQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_yBZ9ExKsEeWPr7pxbi20Rg" name="End - Procurement request succeeded" incoming="_yBZ9gBKsEeWPr7pxbi20Rg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_j3FiTT79EeeFUpJtjfPkKQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_j3FiTj79EeeFUpJtjfPkKQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_j3FiTz79EeeFUpJtjfPkKQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_fDZZwBK3EeWPr7pxbi20Rg" name="Is aborted requested?" outgoing="_fEY4QBK3EeWPr7pxbi20Rg _nvausBK3EeWPr7pxbi20Rg" incoming="_yBZ9fRKsEeWPr7pxbi20Rg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_j3FiVT79EeeFUpJtjfPkKQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_j3FiVj79EeeFUpJtjfPkKQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_j3FiVz79EeeFUpJtjfPkKQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_25P18NobEem3nK4z4KeV0A" text="Note that for testing puporse a single user can do all the tasks in this process"/>
        <elements xmi:type="process:ServiceTask" xmi:id="_-98dcNohEem3nK4z4KeV0A" name="Create quotation for each selected suppliers" outgoing="_--IqsNohEem3nK4z4KeV0A" incoming="_el_woNofEem3nK4z4KeV0A">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_3NtwcNojEem3nK4z4KeV0A" source="_3NqtINojEem3nK4z4KeV0A"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-99EgdohEem3nK4z4KeV0A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-99EgNohEem3nK4z4KeV0A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-99EgtohEem3nK4z4KeV0A" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_lPReIFEnEeyRA_m9wzMnTg" documentation="use this call to generate the Azure AD token that you need to use in the other REST connectors as header" name="generateSharepointToken" definitionId="rest-post" event="ON_ENTER" ignoreErrors="true" definitionVersion="1.3.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_lPReIVEnEeyRA_m9wzMnTg" definitionId="rest-post" version="1.3.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReIlEnEeyRA_m9wzMnTg" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_lPReI1EnEeyRA_m9wzMnTg" name="prepareOAuthUrl()" content="'https://login.microsoftonline.com/' + sharepointTenant +'/oauth2/v2.0/token'" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_SLADEFkWEeyvmZL7s4onFw" name="sharepointTenant" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReJFEnEeyRA_m9wzMnTg" key="contentType">
                <expression xmi:type="expression:Expression" xmi:id="_lPReJVEnEeyRA_m9wzMnTg" name="application/x-www-form-urlencoded" content="application/x-www-form-urlencoded" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReJlEnEeyRA_m9wzMnTg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_lPReJ1EnEeyRA_m9wzMnTg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReKFEnEeyRA_m9wzMnTg" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_lPReKVEnEeyRA_m9wzMnTg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReKlEnEeyRA_m9wzMnTg" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_lPReK1EnEeyRA_m9wzMnTg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReLFEnEeyRA_m9wzMnTg" key="body">
                <expression xmi:type="expression:Expression" xmi:id="_lPReLVEnEeyRA_m9wzMnTg" name="bodyAuthRequest()" content="'grant_type=client_credentials&amp;client_id='+ azureClientID + '&amp;client_secret='+ azureClientSecret +'&amp;scope=https://graph.microsoft.com/.default'" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_egJa0FkWEeyvmZL7s4onFw" name="azureClientID" typeClassname="java.lang.String"/>
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_egJa0VkWEeyvmZL7s4onFw" name="azureClientSecret" typeClassname="java.lang.String"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReLlEnEeyRA_m9wzMnTg" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_lPReL1EnEeyRA_m9wzMnTg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReMFEnEeyRA_m9wzMnTg" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_lPReMVEnEeyRA_m9wzMnTg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReMlEnEeyRA_m9wzMnTg" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_lPReM1EnEeyRA_m9wzMnTg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReNFEnEeyRA_m9wzMnTg" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_lPReNVEnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReNlEnEeyRA_m9wzMnTg" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_lPReN1EnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReOFEnEeyRA_m9wzMnTg" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_lPReOVEnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReOlEnEeyRA_m9wzMnTg" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_lPReO1EnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPRePFEnEeyRA_m9wzMnTg" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_lPRePVEnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPRePlEnEeyRA_m9wzMnTg" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_lPReP1EnEeyRA_m9wzMnTg" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReQFEnEeyRA_m9wzMnTg" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_lPReQVEnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReQlEnEeyRA_m9wzMnTg" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_lPReQ1EnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReRFEnEeyRA_m9wzMnTg" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_lPReRVEnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReRlEnEeyRA_m9wzMnTg" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_lPReR1EnEeyRA_m9wzMnTg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReSFEnEeyRA_m9wzMnTg" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_lPReSVEnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReSlEnEeyRA_m9wzMnTg" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_lPReS1EnEeyRA_m9wzMnTg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReTFEnEeyRA_m9wzMnTg" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_lPReTVEnEeyRA_m9wzMnTg" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReTlEnEeyRA_m9wzMnTg" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_lPReT1EnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReUFEnEeyRA_m9wzMnTg" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_lPReUVEnEeyRA_m9wzMnTg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReUlEnEeyRA_m9wzMnTg" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_lPReU1EnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReVFEnEeyRA_m9wzMnTg" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_lPReVVEnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReVlEnEeyRA_m9wzMnTg" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_lPReV1EnEeyRA_m9wzMnTg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReWFEnEeyRA_m9wzMnTg" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_lPReWVEnEeyRA_m9wzMnTg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_lPReWlEnEeyRA_m9wzMnTg" key="trust_strategy">
                <expression xmi:type="expression:Expression" xmi:id="_lPReW1EnEeyRA_m9wzMnTg" name="DEFAULT" content="DEFAULT" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_lPReXFEnEeyRA_m9wzMnTg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_lPReXVEnEeyRA_m9wzMnTg" name="sharepointToken" content="sharepointToken" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_lPReXlEnEeyRA_m9wzMnTg" documentation="token generated by AzureAD that you need to use for all REST API calls&#xD;&#xA;" name="sharepointToken" dataType="_yBZ9nxKsEeWPr7pxbi20Rg"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_lPReX1EnEeyRA_m9wzMnTg" name="getTokenFromJson" content="import groovy.json.JsonSlurper&#xD;&#xA;&#xD;&#xA;def slurper = new JsonSlurper()&#xD;&#xA;def object = slurper.parseText(bodyAsString)&#xD;&#xA;&#xD;&#xA;return object.access_token" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                <referencedElements xmi:type="definition:Output" xmi:id="_lPReYFEnEeyRA_m9wzMnTg" name="bodyAsString" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_lPReYVEnEeyRA_m9wzMnTg" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <connectors xmi:type="process:Connector" xmi:id="_8sKmYFEnEeyRA_m9wzMnTg" documentation="create a folder named as your case ID" name="createSharepointFolder" definitionId="rest-post" event="ON_ENTER" ignoreErrors="true" definitionVersion="1.3.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_8sKmYVEnEeyRA_m9wzMnTg" definitionId="rest-post" version="1.3.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmYlEnEeyRA_m9wzMnTg" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmY1EnEeyRA_m9wzMnTg" name="urlCreateFolder" content="'https://graph.microsoft.com/v1.0/drives/'+ sharepointParentFolder +'/root:/Quote%20Requests:/children'" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="parameter:Parameter" xmi:id="_IMi10FnaEeyPio-vlBT1kA" name="sharepointParentFolder" typeClassname="java.lang.String" description="use this parameter to store the ID of the Sharepoint Drive that you need to use as part of the URL for your REST calls&#xD;&#xA;"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmZFEnEeyRA_m9wzMnTg" key="contentType">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmZVEnEeyRA_m9wzMnTg" name="application/json" content="application/json" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmZlEnEeyRA_m9wzMnTg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmZ1EnEeyRA_m9wzMnTg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmaFEnEeyRA_m9wzMnTg" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_8sKmaVEnEeyRA_m9wzMnTg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmalEnEeyRA_m9wzMnTg" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_8sKma1EnEeyRA_m9wzMnTg">
                  <expressions xmi:type="expression:ListExpression" xmi:id="_8sKmbFEnEeyRA_m9wzMnTg">
                    <expressions xmi:type="expression:Expression" xmi:id="_8sKmbVEnEeyRA_m9wzMnTg" name="Authorization" content="Authorization"/>
                    <expressions xmi:type="expression:Expression" xmi:id="_8sKmblEnEeyRA_m9wzMnTg" name="sharepointToken" content="sharepointToken" type="TYPE_VARIABLE">
                      <referencedElements xmi:type="process:Data" xmi:id="_8sKmb1EnEeyRA_m9wzMnTg" documentation="token generated by AzureAD that you need to use for all REST API calls&#xD;&#xA;" name="sharepointToken" dataType="_yBZ9nxKsEeWPr7pxbi20Rg"/>
                    </expressions>
                  </expressions>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmcFEnEeyRA_m9wzMnTg" key="body">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmcVEnEeyRA_m9wzMnTg" name="bodyCreateFolder()" content="return '{&quot;name&quot;: &quot;'+ request.caseId.toString() +'&quot;,  &quot;folder&quot;: {  },  &quot;@microsoft.graph.conflictBehavior&quot;: &quot;rename&quot;}'" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_8sKmclEnEeyRA_m9wzMnTg" name="request" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Request"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmc1EnEeyRA_m9wzMnTg" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmdFEnEeyRA_m9wzMnTg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmdVEnEeyRA_m9wzMnTg" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmdlEnEeyRA_m9wzMnTg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmd1EnEeyRA_m9wzMnTg" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmeFEnEeyRA_m9wzMnTg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmeVEnEeyRA_m9wzMnTg" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmelEnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKme1EnEeyRA_m9wzMnTg" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmfFEnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmfVEnEeyRA_m9wzMnTg" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmflEnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmf1EnEeyRA_m9wzMnTg" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmgFEnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmgVEnEeyRA_m9wzMnTg" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmglEnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmg1EnEeyRA_m9wzMnTg" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmhFEnEeyRA_m9wzMnTg" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmhVEnEeyRA_m9wzMnTg" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmhlEnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmh1EnEeyRA_m9wzMnTg" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmiFEnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmiVEnEeyRA_m9wzMnTg" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmilEnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmi1EnEeyRA_m9wzMnTg" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmjFEnEeyRA_m9wzMnTg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmjVEnEeyRA_m9wzMnTg" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmjlEnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmj1EnEeyRA_m9wzMnTg" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmkFEnEeyRA_m9wzMnTg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmkVEnEeyRA_m9wzMnTg" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmklEnEeyRA_m9wzMnTg" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmk1EnEeyRA_m9wzMnTg" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmlFEnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmlVEnEeyRA_m9wzMnTg" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmllEnEeyRA_m9wzMnTg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKml1EnEeyRA_m9wzMnTg" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmmFEnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmmVEnEeyRA_m9wzMnTg" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmmlEnEeyRA_m9wzMnTg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmm1EnEeyRA_m9wzMnTg" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmnFEnEeyRA_m9wzMnTg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmnVEnEeyRA_m9wzMnTg" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmnlEnEeyRA_m9wzMnTg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_8sKmn1EnEeyRA_m9wzMnTg" key="trust_strategy">
                <expression xmi:type="expression:Expression" xmi:id="_8sKmoFEnEeyRA_m9wzMnTg" name="DEFAULT" content="DEFAULT" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_8sKmoVEnEeyRA_m9wzMnTg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_8sKmolEnEeyRA_m9wzMnTg" name="sharepointCaseFolder" content="sharepointCaseFolder" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_8sKmo1EnEeyRA_m9wzMnTg" documentation="the name of the folder created by the process" name="sharepointCaseFolder" dataType="_yBZ9nxKsEeWPr7pxbi20Rg"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_8sKmpFEnEeyRA_m9wzMnTg" name="getNewFolderName()" content="import groovy.json.JsonSlurper&#xD;&#xA;&#xD;&#xA;def slurper = new JsonSlurper()&#xD;&#xA;def object = slurper.parseText(bodyAsString)&#xD;&#xA;&#xD;&#xA;return object.name" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                <referencedElements xmi:type="definition:Output" xmi:id="_8sKmpVEnEeyRA_m9wzMnTg" name="bodyAsString" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_8sKmplEnEeyRA_m9wzMnTg" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <operations xmi:type="expression:Operation" xmi:id="_D1-jYNoiEem3nK4z4KeV0A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_D1-jYdoiEem3nK4z4KeV0A" name="quotations" content="quotations" type="TYPE_VARIABLE" returnType="java.util.List">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_EaoIkNoiEem3nK4z4KeV0A" name="quotations" multiple="true" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Quotation"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_D1-jYtoiEem3nK4z4KeV0A" name="createQuotationForEachSelectedSuppliers" content="import com.company.model.Quotation&#xA;import com.company.model.Supplier;&#xA;&#xA;initialSuppliersSelection.collect { supplier ->&#xA;&#x9;new Quotation(request: request, supplier: supplier, status: 'Pending')&#xA;}" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_WPFosNoiEem3nK4z4KeV0A" name="request" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Request"/>
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_WPFosdoiEem3nK4z4KeV0A" documentation="This variables is initialized with existing suppliers selected by the user when starting the process.&#xA;Contract receive a list of suppliers ids that are used to retrieve suppliers information using a script defined in this business variable default value." name="initialSuppliersSelection" multiple="true" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Supplier"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_D1-jY9oiEem3nK4z4KeV0A" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_-99Eg9ohEem3nK4z4KeV0A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_-99EhNohEem3nK4z4KeV0A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_-99EhdohEem3nK4z4KeV0A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_-99Eh9ohEem3nK4z4KeV0A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_-99EhtohEem3nK4z4KeV0A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_n1-KYNojEem3nK4z4KeV0A" text="User start the process with a summary and description of the request and a selection of potential suppliers."/>
        <elements xmi:type="process:TextAnnotation" xmi:id="_3NqtINojEem3nK4z4KeV0A" text="This task create one quotation object per selected supplier using an operation"/>
        <elements xmi:type="process:TextAnnotation" xmi:id="_8umwsNokEem3nK4z4KeV0A" text="User will select the supplier with the best quotation. If of the supplier is stored in the request business object."/>
        <elements xmi:type="process:TextAnnotation" xmi:id="_KO1bgNolEem3nK4z4KeV0A" text="Update the request status. You may configure the Azure and Sharepoint credentials in the process parameters. "/>
        <filters xmi:type="process:ActorFilter" xmi:id="_zVaWgBTdEeWRxqJe6ExNNg" name="processInitiatorForRequestorLane" definitionId="bonita-actorfilter-initiator" definitionVersion="1.0">
          <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_zVaWgRTdEeWRxqJe6ExNNg" definitionId="bonita-actorfilter-initiator" version="1.0">
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zVaWghTdEeWRxqJe6ExNNg" key="autoAssign">
              <expression xmi:type="expression:Expression" xmi:id="_j3FiXD79EeeFUpJtjfPkKQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </parameters>
          </configuration>
        </filters>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_yBZ9GBKsEeWPr7pxbi20Rg" name="Suppliers" actor="_yBZ9gxKsEeWPr7pxbi20Rg">
        <elements xmi:type="process:Task" xmi:id="_yBZ9GRKsEeWPr7pxbi20Rg" name="Complete quotation" outgoing="_yBZ9ehKsEeWPr7pxbi20Rg" incoming="_--IqsNohEem3nK4z4KeV0A" type="PARALLEL" collectionDataToMultiInstantiate="_yBZ9ShKsEeWPr7pxbi20Rg" overrideActorsOfTheLane="false">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_9zNdwNojEem3nK4z4KeV0A" source="_9zJMUNojEem3nK4z4KeV0A"/>
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_OY754NokEem3nK4z4KeV0A" source="_OY3BYNokEem3nK4z4KeV0A"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_j3E68T79EeeFUpJtjfPkKQ" name="displayName()" content="'Complete quotation - ' + request.caseId.toString()" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_CUCewFExEeyRA_m9wzMnTg" name="request" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Request"/>
          </dynamicLabel>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_j3E68j79EeeFUpJtjfPkKQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_j3E68z79EeeFUpJtjfPkKQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_yBZ9HhKsEeWPr7pxbi20Rg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_j3Fh9z79EeeFUpJtjfPkKQ" name="quotation" content="quotation" type="TYPE_VARIABLE" returnType="com.company.model.Quotation">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Orn4SNoXEem3nK4z4KeV0A" name="quotation" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Quotation"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_j3Fh-T79EeeFUpJtjfPkKQ" name="hasSupplierAccepted" content="hasSupplierAccepted" type="TYPE_CONTRACT_INPUT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Orn4StoXEem3nK4z4KeV0A" name="hasSupplierAccepted" type="BOOLEAN" description="Whether supplier has accepted to provide a quotation">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_Orn4YdoXEem3nK4z4KeV0A"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_yBZ9JBKsEeWPr7pxbi20Rg" type="JAVA_METHOD" expression="setHasSupplierAccepted">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_yBZ9JRKsEeWPr7pxbi20Rg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_j3Fh_D79EeeFUpJtjfPkKQ" name="quotation" content="quotation" type="TYPE_VARIABLE" returnType="com.company.model.Quotation">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Orn4TdoXEem3nK4z4KeV0A" name="quotation" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Quotation"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_j3Fh_j79EeeFUpJtjfPkKQ" name="price" content="price" type="TYPE_CONTRACT_INPUT" returnType="java.lang.Double">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Orn4T9oXEem3nK4z4KeV0A" name="price" type="DECIMAL" description="The quotation total price">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_Orn4YtoXEem3nK4z4KeV0A"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_yBZ9KxKsEeWPr7pxbi20Rg" type="JAVA_METHOD" expression="setProposedPrice">
              <inputTypes>java.lang.Double</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_yBZ9LBKsEeWPr7pxbi20Rg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_j3FiAT79EeeFUpJtjfPkKQ" name="quotation" content="quotation" type="TYPE_VARIABLE" returnType="com.company.model.Quotation">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Orn4UtoXEem3nK4z4KeV0A" name="quotation" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Quotation"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_j3FiAz79EeeFUpJtjfPkKQ" name="comments" content="comments" type="TYPE_CONTRACT_INPUT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Orn4VNoXEem3nK4z4KeV0A" name="comments" description="Supplier's comments">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_OrofUNoXEem3nK4z4KeV0A"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_yBZ9MhKsEeWPr7pxbi20Rg" type="JAVA_METHOD" expression="setComments">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_qO-g8BMxEeWpdIGsOJwTbQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_j3FiBj79EeeFUpJtjfPkKQ" name="quotation" content="quotation" type="TYPE_VARIABLE" returnType="com.company.model.Quotation">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Orn4V9oXEem3nK4z4KeV0A" name="quotation" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Quotation"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_j3FiCD79EeeFUpJtjfPkKQ" name="Completed" content="Completed"/>
            <operator xmi:type="expression:Operator" xmi:id="_qO-g8RMxEeWpdIGsOJwTbQ" type="JAVA_METHOD" expression="setStatus">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_j3E6-D79EeeFUpJtjfPkKQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_j3E6-T79EeeFUpJtjfPkKQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_j3E6-j79EeeFUpJtjfPkKQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_j3E6-z79EeeFUpJtjfPkKQ" name="quotation" content="quotation" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="com.company.model.Quotation" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_j3E6_D79EeeFUpJtjfPkKQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_yBZ9OhKsEeWPr7pxbi20Rg">
            <targetForm xmi:type="expression:Expression" xmi:id="_j3FiET79EeeFUpJtjfPkKQ" name="procurementCompleteQuotationForm" content="c28d545b-6571-4107-b577-a547a8c21915" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_yBZ9PBKsEeWPr7pxbi20Rg">
            <inputs xmi:type="process:ContractInput" xmi:id="_j3FiFj79EeeFUpJtjfPkKQ" name="hasSupplierAccepted" type="BOOLEAN" description="Whether supplier has accepted to provide a quotation">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_j3FiFz79EeeFUpJtjfPkKQ"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_j3FiGD79EeeFUpJtjfPkKQ" name="price" type="DECIMAL" description="The quotation total price">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_j3FiGT79EeeFUpJtjfPkKQ"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_j3FiGj79EeeFUpJtjfPkKQ" name="comments" description="Supplier's comments">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_j3FiGz79EeeFUpJtjfPkKQ"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_j3E7AT79EeeFUpJtjfPkKQ" name="3600000" content="3600000" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_GwE_0BK3EeWPr7pxbi20Rg" name="Update request after quotations received" outgoing="_GwyxgBK3EeWPr7pxbi20Rg" incoming="_yBZ9ehKsEeWPr7pxbi20Rg">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_kxug0NokEem3nK4z4KeV0A" source="_kxsroNokEem3nK4z4KeV0A"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_j3FiMT79EeeFUpJtjfPkKQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_j3FiMj79EeeFUpJtjfPkKQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_j3FiMz79EeeFUpJtjfPkKQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_j3FiND79EeeFUpJtjfPkKQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_j3FiNT79EeeFUpJtjfPkKQ" name="request" content="request" type="TYPE_VARIABLE" returnType="com.company.model.Request">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Orofd9oXEem3nK4z4KeV0A" name="request" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Request"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_j3FiNz79EeeFUpJtjfPkKQ" name="Pending for review" content="Pending for review"/>
            <operator xmi:type="expression:Operator" xmi:id="_j3FiOD79EeeFUpJtjfPkKQ" type="JAVA_METHOD" expression="setStatus">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_j3FiOT79EeeFUpJtjfPkKQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_j3FiOj79EeeFUpJtjfPkKQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_j3FiOz79EeeFUpJtjfPkKQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_j3FiPD79EeeFUpJtjfPkKQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_j3FiPT79EeeFUpJtjfPkKQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_nvNTUBK3EeWPr7pxbi20Rg" name="Abort request" outgoing="_w6FugBK3EeWPr7pxbi20Rg" incoming="_nvausBK3EeWPr7pxbi20Rg">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_NLVB0NolEem3nK4z4KeV0A" source="_NLTzsNolEem3nK4z4KeV0A"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_j3FiPz79EeeFUpJtjfPkKQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_j3FiQD79EeeFUpJtjfPkKQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_j3FiQT79EeeFUpJtjfPkKQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_j3FiQj79EeeFUpJtjfPkKQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_j3FiQz79EeeFUpJtjfPkKQ" name="request" content="request" type="TYPE_VARIABLE" returnType="com.company.model.Request">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_OrpGZtoXEem3nK4z4KeV0A" name="request" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Request"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_j3FiRT79EeeFUpJtjfPkKQ" name="Aborted" content="Aborted"/>
            <operator xmi:type="expression:Operator" xmi:id="_j3FiRj79EeeFUpJtjfPkKQ" type="JAVA_METHOD" expression="setStatus">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_j3FiRz79EeeFUpJtjfPkKQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_j3FiSD79EeeFUpJtjfPkKQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_j3FiST79EeeFUpJtjfPkKQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_j3FiSj79EeeFUpJtjfPkKQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_j3FiSz79EeeFUpJtjfPkKQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_w5_A0BK3EeWPr7pxbi20Rg" name="End - Procurement request aborted" incoming="_w6FugBK3EeWPr7pxbi20Rg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_j3FiUT79EeeFUpJtjfPkKQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_j3FiUj79EeeFUpJtjfPkKQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_j3FiUz79EeeFUpJtjfPkKQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_9zJMUNojEem3nK4z4KeV0A" text="This task has multiple instances (i.e. copies): one per quotation object (meaning one for each potential suppliers)"/>
        <elements xmi:type="process:TextAnnotation" xmi:id="_OY3BYNokEem3nK4z4KeV0A" text="Suppliers will provide information such as wether or not he accepts to provide a quotation and the amount. Operations on this task will update the appropriate quotation business object."/>
        <elements xmi:type="process:TextAnnotation" xmi:id="_kxsroNokEem3nK4z4KeV0A" text="This task update the request status"/>
        <elements xmi:type="process:TextAnnotation" xmi:id="_NLTzsNolEem3nK4z4KeV0A" text="Update the request status to &quot;Aborted&quot;"/>
        <filters xmi:type="process:ActorFilter" xmi:id="_xovZUBTdEeWRxqJe6ExNNg" name="processInitatorForSupplierLane" definitionId="bonita-actorfilter-initiator" definitionVersion="1.0">
          <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_xovZURTdEeWRxqJe6ExNNg" definitionId="bonita-actorfilter-initiator" version="1.0">
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_xovZUhTdEeWRxqJe6ExNNg" key="autoAssign">
              <expression xmi:type="expression:Expression" xmi:id="_j3FiXT79EeeFUpJtjfPkKQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </parameters>
          </configuration>
        </filters>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_yBZ9ShKsEeWPr7pxbi20Rg" name="quotations" multiple="true" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Quotation">
        <defaultValue xmi:type="expression:Expression" xmi:id="_MpPAoT8QEeevVaHUwfkI8w" name="" content="" interpreter="GROOVY"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_yBZ9TBKsEeWPr7pxbi20Rg" name="request" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Request">
        <defaultValue xmi:type="expression:Expression" xmi:id="_yPw9Fj8QEeevVaHUwfkI8w" name="init_request()" content="import java.time.LocalDate&#xA;&#xA;import org.bonitasoft.engine.identity.UserNotFoundException&#xA;&#xA;import com.company.model.Request&#xA;&#xA;def processInitiator = apiAccessor.getIdentityAPI().getUser(apiAccessor.getProcessAPI()&#xA;&#x9;&#x9;&#x9;.getProcessInstance(processInstanceId)&#xA;&#x9;&#x9;&#x9;.getStartedBy())&#xA;&#x9;&#x9;&#x9;&#xA;&#xA;new Request(summary: summary,&#xA;&#x9; description: description,&#xA;&#x9; creationDate: LocalDate.now(),&#xA;&#x9; createdBy: &quot;${processInitiator.firstName} ${processInitiator.lastName}&quot;.toString(),&#xA;&#x9; status: 'Pending for quotations',&#xA;&#x9; caseId: processInstanceId);" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Request">
          <referencedElements xmi:type="expression:Expression" xmi:id="_X7ioEKvwEeufhfjpkavPmQ" name="processInstanceId" content="processInstanceId" type="TYPE_ENGINE_CONSTANT" returnType="java.lang.Long"/>
          <referencedElements xmi:type="expression:Expression" xmi:id="_X7ioEavwEeufhfjpkavPmQ" name="apiAccessor" content="apiAccessor" type="TYPE_ENGINE_CONSTANT" returnType="org.bonitasoft.engine.api.APIAccessor"/>
          <referencedElements xmi:type="process:ContractInput" xmi:id="_X7jPIKvwEeufhfjpkavPmQ" name="summary" description="Request summary">
            <mapping xmi:type="process:ContractInputMapping" xmi:id="_X7jPIavwEeufhfjpkavPmQ"/>
          </referencedElements>
          <referencedElements xmi:type="process:ContractInput" xmi:id="_X7jPIqvwEeufhfjpkavPmQ" name="description" description="Request description">
            <mapping xmi:type="process:ContractInputMapping" xmi:id="_X7jPI6vwEeufhfjpkavPmQ"/>
          </referencedElements>
        </defaultValue>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_7ghUUNohEem3nK4z4KeV0A" documentation="This variables is initialized with existing suppliers selected by the user when starting the process.&#xA;Contract receive a list of suppliers ids that are used to retrieve suppliers information using a script defined in this business variable default value." name="initialSuppliersSelection" multiple="true" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Supplier">
        <defaultValue xmi:type="expression:Expression" xmi:id="_7ghUUdohEem3nK4z4KeV0A" name="createTheInitialSuppliersSelectionBasedOnSuppliersIds" content="supplierIds.collect { supplierId ->&#x9;supplierDAO.findById(Long.valueOf(supplierId)) }" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
          <referencedElements xmi:type="expression:Expression" xmi:id="_pgcAwNomEem3nK4z4KeV0A" name="supplierDAO" content="supplierDAO" type="TYPE_BUSINESS_OBJECT_DAO" returnType="com.company.model.SupplierDAO" returnTypeFixed="true"/>
          <referencedElements xmi:type="process:ContractInput" xmi:id="_pgcAwdomEem3nK4z4KeV0A" name="supplierIds" description="List of suitable suppliers" multiple="true">
            <mapping xmi:type="process:ContractInputMapping" xmi:id="_pgcAwtomEem3nK4z4KeV0A"/>
          </referencedElements>
        </defaultValue>
      </data>
      <data xmi:type="process:Data" xmi:id="_uknSUFEmEeyRA_m9wzMnTg" documentation="the name of the folder created by the process" name="sharepointCaseFolder" dataType="_yBZ9nxKsEeWPr7pxbi20Rg">
        <defaultValue xmi:type="expression:Expression" xmi:id="_uknSUVEmEeyRA_m9wzMnTg" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_ytBSIFEmEeyRA_m9wzMnTg" documentation="token generated by AzureAD that you need to use for all REST API calls&#xD;&#xA;" name="sharepointToken" dataType="_yBZ9nxKsEeWPr7pxbi20Rg">
        <defaultValue xmi:type="expression:Expression" xmi:id="_ytBSIVEmEeyRA_m9wzMnTg" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_7slOIFEmEeyRA_m9wzMnTg" documentation="store the response message of the upload rest call&#xD;&#xA;" name="sharepointWordUploadMessage" dataType="_yBZ9nxKsEeWPr7pxbi20Rg">
        <defaultValue xmi:type="expression:Expression" xmi:id="_7slOIVEmEeyRA_m9wzMnTg" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_-sTHkFEmEeyRA_m9wzMnTg" documentation="save the response of your pdf upload rest call" name="sharepointPDFUploadMessage" dataType="_yBZ9nxKsEeWPr7pxbi20Rg">
        <defaultValue xmi:type="expression:Expression" xmi:id="_-sTHkVEmEeyRA_m9wzMnTg" content=""/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_yBZ9cRKsEeWPr7pxbi20Rg">
        <targetForm xmi:type="expression:Expression" xmi:id="_j3FiEj79EeeFUpJtjfPkKQ" name="procurementRequestCreationForm" content="da18acb0-d393-46d7-90ca-168bccf8904b" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_yBZ9dBKsEeWPr7pxbi20Rg">
        <targetForm xmi:type="expression:Expression" xmi:id="_j3FiEz79EeeFUpJtjfPkKQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_yBZ9ehKsEeWPr7pxbi20Rg" target="_GwE_0BK3EeWPr7pxbi20Rg" source="_yBZ9GRKsEeWPr7pxbi20Rg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_yBZ9exKsEeWPr7pxbi20Rg"/>
        <condition xmi:type="expression:Expression" xmi:id="_j3GJAz79EeeFUpJtjfPkKQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_yBZ9fRKsEeWPr7pxbi20Rg" target="_fDZZwBK3EeWPr7pxbi20Rg" source="_yBZ85hKsEeWPr7pxbi20Rg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_yBZ9fhKsEeWPr7pxbi20Rg"/>
        <condition xmi:type="expression:Expression" xmi:id="_j3GJBT79EeeFUpJtjfPkKQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_yBZ9gBKsEeWPr7pxbi20Rg" target="_yBZ9ExKsEeWPr7pxbi20Rg" source="_yBZ9CRKsEeWPr7pxbi20Rg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_yBZ9gRKsEeWPr7pxbi20Rg"/>
        <condition xmi:type="expression:Expression" xmi:id="_j3GJBz79EeeFUpJtjfPkKQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GwyxgBK3EeWPr7pxbi20Rg" target="_yBZ85hKsEeWPr7pxbi20Rg" source="_GwE_0BK3EeWPr7pxbi20Rg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GwyxgRK3EeWPr7pxbi20Rg"/>
        <condition xmi:type="expression:Expression" xmi:id="_j3GJCT79EeeFUpJtjfPkKQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_fEY4QBK3EeWPr7pxbi20Rg" name="No" target="_yBZ9CRKsEeWPr7pxbi20Rg" source="_fDZZwBK3EeWPr7pxbi20Rg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_fEY4QRK3EeWPr7pxbi20Rg"/>
        <condition xmi:type="expression:Expression" xmi:id="_j3GJCz79EeeFUpJtjfPkKQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nvausBK3EeWPr7pxbi20Rg" name="Yes" target="_nvNTUBK3EeWPr7pxbi20Rg" source="_fDZZwBK3EeWPr7pxbi20Rg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nvausRK3EeWPr7pxbi20Rg"/>
        <condition xmi:type="expression:Expression" xmi:id="_j3GJDT79EeeFUpJtjfPkKQ" name="hasNotSelectedSupplier" content="request.selectedSupplier == null" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_OrptkNoXEem3nK4z4KeV0A" name="request" dataType="_yBZ9ohKsEeWPr7pxbi20Rg" className="com.company.model.Request"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_w6FugBK3EeWPr7pxbi20Rg" target="_w5_A0BK3EeWPr7pxbi20Rg" source="_nvNTUBK3EeWPr7pxbi20Rg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_w6GVkBK3EeWPr7pxbi20Rg"/>
        <condition xmi:type="expression:Expression" xmi:id="_j3GJED79EeeFUpJtjfPkKQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_el_woNofEem3nK4z4KeV0A" target="_-98dcNohEem3nK4z4KeV0A" source="_yBZ84RKsEeWPr7pxbi20Rg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_el_wodofEem3nK4z4KeV0A"/>
        <condition xmi:type="expression:Expression" xmi:id="_el_wotofEem3nK4z4KeV0A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_--IqsNohEem3nK4z4KeV0A" target="_yBZ9GRKsEeWPr7pxbi20Rg" source="_-98dcNohEem3nK4z4KeV0A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_--IqsdohEem3nK4z4KeV0A"/>
        <condition xmi:type="expression:Expression" xmi:id="_--IqstohEem3nK4z4KeV0A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_yBZ9gxKsEeWPr7pxbi20Rg" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_JeoowFEnEeyRA_m9wzMnTg" name="sharepointParentFolder" typeClassname="java.lang.String" description="use this parameter to store the ID of the Sharepoint Drive that you need to use as part of the URL for your REST calls&#xD;&#xA;"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_sVz_kFkVEeyvmZL7s4onFw" name="sharepointTenant" typeClassname="java.lang.String" description="The directory tenant that you want to request permission from. This can be in GUID or friendly name format (e.g. abcdef..onmicrosoft.com)"/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_T_h7wFkWEeyvmZL7s4onFw" name="azureClientID" typeClassname="java.lang.String" description="The Application ID that the Azure app registration portal assigned when you registered your app."/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_UtX5MFkWEeyvmZL7s4onFw" name="azureClientSecret" typeClassname="java.lang.String" description="The Application Secret that you generated for your app in the app registration portal. Ensure that it is URL encoded."/>
      <contract xmi:type="process:Contract" xmi:id="_yBZ9hBKsEeWPr7pxbi20Rg">
        <inputs xmi:type="process:ContractInput" xmi:id="_j3FiHD79EeeFUpJtjfPkKQ" name="summary" description="Request summary">
          <mapping xmi:type="process:ContractInputMapping" xmi:id="_j3FiHT79EeeFUpJtjfPkKQ"/>
        </inputs>
        <inputs xmi:type="process:ContractInput" xmi:id="_j3FiHj79EeeFUpJtjfPkKQ" name="description" description="Request description">
          <mapping xmi:type="process:ContractInputMapping" xmi:id="_j3FiHz79EeeFUpJtjfPkKQ"/>
        </inputs>
        <inputs xmi:type="process:ContractInput" xmi:id="_j3FiID79EeeFUpJtjfPkKQ" name="supplierIds" description="List of suitable suppliers" multiple="true">
          <mapping xmi:type="process:ContractInputMapping" xmi:id="_j3FiIT79EeeFUpJtjfPkKQ"/>
        </inputs>
      </contract>
      <documents xmi:type="process:Document" xmi:id="_8PDwcFEjEeyRA_m9wzMnTg" name="quoteRequestTemplate" defaultValueIdOfDocumentStore="QuoteRequestTemplate.docx" documentType="INTERNAL">
        <mimeType xmi:type="expression:Expression" xmi:id="_8PDwcVEjEeyRA_m9wzMnTg" name="" content="" returnTypeFixed="true"/>
        <url xmi:type="expression:Expression" xmi:id="_8PDwclEjEeyRA_m9wzMnTg" name="" content="" returnTypeFixed="true"/>
        <initialMultipleContent xmi:type="expression:Expression" xmi:id="_8PDwc1EjEeyRA_m9wzMnTg" name="" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List" returnTypeFixed="true"/>
      </documents>
      <documents xmi:type="process:Document" xmi:id="__DY5QFEjEeyRA_m9wzMnTg" name="quoteRequestWord">
        <mimeType xmi:type="expression:Expression" xmi:id="__DY5QVEjEeyRA_m9wzMnTg" name="" content="" returnTypeFixed="true"/>
        <url xmi:type="expression:Expression" xmi:id="__DY5QlEjEeyRA_m9wzMnTg" name="" content="" returnTypeFixed="true"/>
        <initialMultipleContent xmi:type="expression:Expression" xmi:id="__DY5Q1EjEeyRA_m9wzMnTg" name="" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List" returnTypeFixed="true"/>
      </documents>
      <documents xmi:type="process:Document" xmi:id="__uu8UFEjEeyRA_m9wzMnTg" name="quoteRequestPDF">
        <mimeType xmi:type="expression:Expression" xmi:id="__uu8UVEjEeyRA_m9wzMnTg" name="" content="" returnTypeFixed="true"/>
        <url xmi:type="expression:Expression" xmi:id="__uu8UlEjEeyRA_m9wzMnTg" name="" content="" returnTypeFixed="true"/>
        <initialMultipleContent xmi:type="expression:Expression" xmi:id="__uu8U1EjEeyRA_m9wzMnTg" name="" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List" returnTypeFixed="true"/>
      </documents>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_yBZ9ixKsEeWPr7pxbi20Rg">
        <name xmi:type="expression:Expression" xmi:id="_j3GJET79EeeFUpJtjfPkKQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_j3GJEj79EeeFUpJtjfPkKQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_yBZ9jhKsEeWPr7pxbi20Rg">
        <name xmi:type="expression:Expression" xmi:id="_j3GJEz79EeeFUpJtjfPkKQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_j3GJFD79EeeFUpJtjfPkKQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_yBZ9kRKsEeWPr7pxbi20Rg">
        <name xmi:type="expression:Expression" xmi:id="_j3GJFT79EeeFUpJtjfPkKQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_j3GJFj79EeeFUpJtjfPkKQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_yBZ9lBKsEeWPr7pxbi20Rg">
        <name xmi:type="expression:Expression" xmi:id="_j3GJFz79EeeFUpJtjfPkKQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_j3GJGD79EeeFUpJtjfPkKQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_yBZ9lxKsEeWPr7pxbi20Rg">
        <name xmi:type="expression:Expression" xmi:id="_j3GJGT79EeeFUpJtjfPkKQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_j3GJGj79EeeFUpJtjfPkKQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_yBZ9mhKsEeWPr7pxbi20Rg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_yBZ9mxKsEeWPr7pxbi20Rg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_yBZ9nBKsEeWPr7pxbi20Rg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_yBZ9nRKsEeWPr7pxbi20Rg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_yBZ9nhKsEeWPr7pxbi20Rg" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_yBZ9nxKsEeWPr7pxbi20Rg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_yBZ9oBKsEeWPr7pxbi20Rg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_yBZ9oRKsEeWPr7pxbi20Rg" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_yBZ9ohKsEeWPr7pxbi20Rg" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_yBZ9oxKsEeWPr7pxbi20Rg" type="Process" element="_yBZV0BKsEeWPr7pxbi20Rg" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_yBZ9pBKsEeWPr7pxbi20Rg" type="2007" element="_yBZV0RKsEeWPr7pxbi20Rg">
      <children xmi:type="notation:DecorationNode" xmi:id="_yBZ9pRKsEeWPr7pxbi20Rg" type="5008" element="_yBZV0RKsEeWPr7pxbi20Rg"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_yBZ9phKsEeWPr7pxbi20Rg" type="7001" element="_yBZV0RKsEeWPr7pxbi20Rg">
        <children xmi:type="notation:Node" xmi:id="_j3GJLD79EeeFUpJtjfPkKQ" type="3007" element="_yBZ84BKsEeWPr7pxbi20Rg">
          <children xmi:type="notation:DecorationNode" xmi:id="_yBZ9qBKsEeWPr7pxbi20Rg" type="5007" element="_yBZ84BKsEeWPr7pxbi20Rg"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_yBZ9qRKsEeWPr7pxbi20Rg" type="7002" element="_yBZ84BKsEeWPr7pxbi20Rg">
            <children xmi:type="notation:Shape" xmi:id="_yBZ9qhKsEeWPr7pxbi20Rg" type="3002" element="_yBZ84RKsEeWPr7pxbi20Rg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_j3GJRT79EeeFUpJtjfPkKQ" type="5024" element="_yBZ84RKsEeWPr7pxbi20Rg">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_yBZ9rBKsEeWPr7pxbi20Rg" y="-64"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yBZ9rRKsEeWPr7pxbi20Rg" x="303" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_yBZ9rhKsEeWPr7pxbi20Rg" type="3005" element="_yBZ85hKsEeWPr7pxbi20Rg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_j3GJSD79EeeFUpJtjfPkKQ" type="5005" element="_yBZ85hKsEeWPr7pxbi20Rg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yBZ9sBKsEeWPr7pxbi20Rg" x="502" y="37" width="144" height="72"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_yBZ9sRKsEeWPr7pxbi20Rg" type="3027" element="_yBZ9CRKsEeWPr7pxbi20Rg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_j3GJSj79EeeFUpJtjfPkKQ" type="5017" element="_yBZ9CRKsEeWPr7pxbi20Rg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yBZ9sxKsEeWPr7pxbi20Rg" x="811" y="35" width="147" height="72"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_yBZ9tBKsEeWPr7pxbi20Rg" type="3003" element="_yBZ9ExKsEeWPr7pxbi20Rg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_j3GJTD79EeeFUpJtjfPkKQ" type="5025" element="_yBZ9ExKsEeWPr7pxbi20Rg">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_yBZ9thKsEeWPr7pxbi20Rg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yBZ9txKsEeWPr7pxbi20Rg" x="1090" y="52"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_fDb2ABK3EeWPr7pxbi20Rg" type="3008" element="_fDZZwBK3EeWPr7pxbi20Rg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_j3GJTz79EeeFUpJtjfPkKQ" type="5026" element="_fDZZwBK3EeWPr7pxbi20Rg">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_fDb2AxK3EeWPr7pxbi20Rg" y="-60"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fDb2ARK3EeWPr7pxbi20Rg" x="692" y="45"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_25RrINobEem3nK4z4KeV0A" type="3015" element="_25P18NobEem3nK4z4KeV0A">
              <children xmi:type="notation:DecorationNode" xmi:id="_25SSMNobEem3nK4z4KeV0A" type="5010" element="_25P18NobEem3nK4z4KeV0A"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_25RrIdobEem3nK4z4KeV0A"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_25RrItobEem3nK4z4KeV0A" fontName="Noto Sans"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_25RrI9obEem3nK4z4KeV0A"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_25RrJNobEem3nK4z4KeV0A" x="50" y="68" width="224" height="69"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-99rkNohEem3nK4z4KeV0A" type="3027" element="_-98dcNohEem3nK4z4KeV0A" fontName="Noto Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_-99rktohEem3nK4z4KeV0A" type="5017" element="_-98dcNohEem3nK4z4KeV0A"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-99rkdohEem3nK4z4KeV0A" x="248" y="250" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_n1_YgNojEem3nK4z4KeV0A" type="3015" element="_n1-KYNojEem3nK4z4KeV0A">
              <children xmi:type="notation:DecorationNode" xmi:id="_n1__kNojEem3nK4z4KeV0A" type="5010" element="_n1-KYNojEem3nK4z4KeV0A"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_n1_YgdojEem3nK4z4KeV0A"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_n1_YgtojEem3nK4z4KeV0A" fontName="Noto Sans"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_n1_Yg9ojEem3nK4z4KeV0A"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_n1_YhNojEem3nK4z4KeV0A" x="50" y="152" width="224" height="83"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_3NqtIdojEem3nK4z4KeV0A" type="3015" element="_3NqtINojEem3nK4z4KeV0A">
              <children xmi:type="notation:DecorationNode" xmi:id="_3NrUMNojEem3nK4z4KeV0A" type="5010" element="_3NqtINojEem3nK4z4KeV0A"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_3NqtItojEem3nK4z4KeV0A"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_3NqtI9ojEem3nK4z4KeV0A" fontName="Noto Sans"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_3NqtJNojEem3nK4z4KeV0A"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3NqtJdojEem3nK4z4KeV0A" x="48" y="255" width="180" height="65"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_8umwsdokEem3nK4z4KeV0A" type="3015" element="_8umwsNokEem3nK4z4KeV0A">
              <children xmi:type="notation:DecorationNode" xmi:id="_8unXwNokEem3nK4z4KeV0A" type="5010" element="_8umwsNokEem3nK4z4KeV0A"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_8umwstokEem3nK4z4KeV0A"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_8umws9okEem3nK4z4KeV0A" fontName="Noto Sans"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_8umwtNokEem3nK4z4KeV0A"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8umwtdokEem3nK4z4KeV0A" x="367" y="136" width="169" height="98"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_KO2CkNolEem3nK4z4KeV0A" type="3015" element="_KO1bgNolEem3nK4z4KeV0A">
              <children xmi:type="notation:DecorationNode" xmi:id="_KO2poNolEem3nK4z4KeV0A" type="5010" element="_KO1bgNolEem3nK4z4KeV0A"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_KO2CkdolEem3nK4z4KeV0A"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_KO2CktolEem3nK4z4KeV0A" fontName="Noto Sans"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_KO2Ck9olEem3nK4z4KeV0A"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KO2ClNolEem3nK4z4KeV0A" x="839" y="140" width="173" height="94"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_yBZ9uBKsEeWPr7pxbi20Rg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_yBZ9uRKsEeWPr7pxbi20Rg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_yBZ9uhKsEeWPr7pxbi20Rg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_yBZ9uxKsEeWPr7pxbi20Rg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yBZ9vBKsEeWPr7pxbi20Rg" x="48" y="10" width="1174" height="362"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_j3GJND79EeeFUpJtjfPkKQ" type="3007" element="_yBZ9GBKsEeWPr7pxbi20Rg">
          <children xmi:type="notation:DecorationNode" xmi:id="_yBZ9vhKsEeWPr7pxbi20Rg" type="5007" element="_yBZ9GBKsEeWPr7pxbi20Rg"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_yBZ9vxKsEeWPr7pxbi20Rg" type="7002" element="_yBZ9GBKsEeWPr7pxbi20Rg">
            <children xmi:type="notation:Shape" xmi:id="_yBZ9wBKsEeWPr7pxbi20Rg" type="3005" element="_yBZ9GRKsEeWPr7pxbi20Rg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_j3GJUj79EeeFUpJtjfPkKQ" type="5005" element="_yBZ9GRKsEeWPr7pxbi20Rg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yBZ9whKsEeWPr7pxbi20Rg" x="250" y="77" width="132" height="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_GwHcEBK3EeWPr7pxbi20Rg" type="3027" element="_GwE_0BK3EeWPr7pxbi20Rg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_j3GJVD79EeeFUpJtjfPkKQ" type="5017" element="_GwE_0BK3EeWPr7pxbi20Rg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GwHcERK3EeWPr7pxbi20Rg" x="519" y="75" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_nvQWoBK3EeWPr7pxbi20Rg" type="3027" element="_nvNTUBK3EeWPr7pxbi20Rg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_j3GJVj79EeeFUpJtjfPkKQ" type="5017" element="_nvNTUBK3EeWPr7pxbi20Rg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nvQWoRK3EeWPr7pxbi20Rg" x="848" y="85"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_w6A2ABK3EeWPr7pxbi20Rg" type="3003" element="_w5_A0BK3EeWPr7pxbi20Rg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_j3GJWD79EeeFUpJtjfPkKQ" type="5025" element="_w5_A0BK3EeWPr7pxbi20Rg">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_w6A2AxK3EeWPr7pxbi20Rg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_w6A2ARK3EeWPr7pxbi20Rg" x="1061" y="95"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_9zJzYNojEem3nK4z4KeV0A" type="3015" element="_9zJMUNojEem3nK4z4KeV0A">
              <children xmi:type="notation:DecorationNode" xmi:id="_9zKacNojEem3nK4z4KeV0A" type="5010" element="_9zJMUNojEem3nK4z4KeV0A"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_9zJzYdojEem3nK4z4KeV0A"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_9zJzYtojEem3nK4z4KeV0A" fontName="Noto Sans"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_9zJzY9ojEem3nK4z4KeV0A"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9zJzZNojEem3nK4z4KeV0A" x="48" y="74" width="180" height="95"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_OY3ocNokEem3nK4z4KeV0A" type="3015" element="_OY3BYNokEem3nK4z4KeV0A">
              <children xmi:type="notation:DecorationNode" xmi:id="_OY4PgNokEem3nK4z4KeV0A" type="5010" element="_OY3BYNokEem3nK4z4KeV0A"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_OY3ocdokEem3nK4z4KeV0A"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_OY3octokEem3nK4z4KeV0A" fontName="Noto Sans"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_OY3oc9okEem3nK4z4KeV0A"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OY3odNokEem3nK4z4KeV0A" x="243" y="168" width="237" height="113"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_kxsrodokEem3nK4z4KeV0A" type="3015" element="_kxsroNokEem3nK4z4KeV0A">
              <children xmi:type="notation:DecorationNode" xmi:id="_kxtSsNokEem3nK4z4KeV0A" type="5010" element="_kxsroNokEem3nK4z4KeV0A"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_kxsrotokEem3nK4z4KeV0A"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_kxsro9okEem3nK4z4KeV0A" fontName="Noto Sans"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_kxsrpNokEem3nK4z4KeV0A"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kxsrpdokEem3nK4z4KeV0A" x="535" y="175" width="113"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_NLTzsdolEem3nK4z4KeV0A" type="3015" element="_NLTzsNolEem3nK4z4KeV0A">
              <children xmi:type="notation:DecorationNode" xmi:id="_NLTzttolEem3nK4z4KeV0A" type="5010" element="_NLTzsNolEem3nK4z4KeV0A"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_NLTzstolEem3nK4z4KeV0A"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_NLTzs9olEem3nK4z4KeV0A" fontName="Noto Sans"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_NLTztNolEem3nK4z4KeV0A"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NLTztdolEem3nK4z4KeV0A" x="832" y="188" width="142"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_yBZ9wxKsEeWPr7pxbi20Rg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_yBZ9xBKsEeWPr7pxbi20Rg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_yBZ9xRKsEeWPr7pxbi20Rg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_yBZ9xhKsEeWPr7pxbi20Rg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yBZ9xxKsEeWPr7pxbi20Rg" x="48" y="362" width="1174" height="341"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_yBZ9yBKsEeWPr7pxbi20Rg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_yBZ9yRKsEeWPr7pxbi20Rg" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_yBZ9yhKsEeWPr7pxbi20Rg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_yBZ9yxKsEeWPr7pxbi20Rg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yBZ9zBKsEeWPr7pxbi20Rg" width="1259" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_yBZ9zRKsEeWPr7pxbi20Rg"/>
    <edges xmi:type="notation:Connector" xmi:id="_yBZ90xKsEeWPr7pxbi20Rg" type="4001" element="_yBZ9ehKsEeWPr7pxbi20Rg" source="_yBZ9wBKsEeWPr7pxbi20Rg" target="_GwHcEBK3EeWPr7pxbi20Rg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_j3GJXz79EeeFUpJtjfPkKQ" type="6001" element="_yBZ9ehKsEeWPr7pxbi20Rg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_j3GJYD79EeeFUpJtjfPkKQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_j3GJYT79EeeFUpJtjfPkKQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_yBZ91xKsEeWPr7pxbi20Rg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_yBZ92BKsEeWPr7pxbi20Rg" type="4001" element="_yBZ9fRKsEeWPr7pxbi20Rg" source="_yBZ9rhKsEeWPr7pxbi20Rg" target="_fDb2ABK3EeWPr7pxbi20Rg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_j3GJYz79EeeFUpJtjfPkKQ" type="6001" element="_yBZ9fRKsEeWPr7pxbi20Rg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_j3GJZD79EeeFUpJtjfPkKQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_j3GJZT79EeeFUpJtjfPkKQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_yBZ93BKsEeWPr7pxbi20Rg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_yBZ93RKsEeWPr7pxbi20Rg" type="4001" element="_yBZ9gBKsEeWPr7pxbi20Rg" source="_yBZ9sRKsEeWPr7pxbi20Rg" target="_yBZ9tBKsEeWPr7pxbi20Rg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_j3GJZz79EeeFUpJtjfPkKQ" type="6001" element="_yBZ9gBKsEeWPr7pxbi20Rg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_j3GJaD79EeeFUpJtjfPkKQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_j3GJaT79EeeFUpJtjfPkKQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_yBZ94RKsEeWPr7pxbi20Rg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Gwz_oBK3EeWPr7pxbi20Rg" type="4001" element="_GwyxgBK3EeWPr7pxbi20Rg" source="_GwHcEBK3EeWPr7pxbi20Rg" target="_yBZ9rhKsEeWPr7pxbi20Rg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_j3GJaz79EeeFUpJtjfPkKQ" type="6001" element="_GwyxgBK3EeWPr7pxbi20Rg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_j3GJbD79EeeFUpJtjfPkKQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_j3GJbT79EeeFUpJtjfPkKQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Gw0msRK3EeWPr7pxbi20Rg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_fEaGYBK3EeWPr7pxbi20Rg" type="4001" element="_fEY4QBK3EeWPr7pxbi20Rg" source="_fDb2ABK3EeWPr7pxbi20Rg" target="_yBZ9sRKsEeWPr7pxbi20Rg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_j3GJbz79EeeFUpJtjfPkKQ" type="6001" element="_fEY4QBK3EeWPr7pxbi20Rg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_j3GJcD79EeeFUpJtjfPkKQ" x="-16" y="16"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_j3GJcT79EeeFUpJtjfPkKQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_fEaGYhK3EeWPr7pxbi20Rg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nvj4oBK3EeWPr7pxbi20Rg" type="4001" element="_nvausBK3EeWPr7pxbi20Rg" source="_fDb2ABK3EeWPr7pxbi20Rg" target="_nvQWoBK3EeWPr7pxbi20Rg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_j3GwED79EeeFUpJtjfPkKQ" type="6001" element="_nvausBK3EeWPr7pxbi20Rg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_j3GwET79EeeFUpJtjfPkKQ" x="-97" y="-12"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_j3GwEj79EeeFUpJtjfPkKQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nvj4ohK3EeWPr7pxbi20Rg" points="[0, 22, -158, -124]$[0, 151, -158, 5]$[108, 151, -50, 5]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_w6G8oBK3EeWPr7pxbi20Rg" type="4001" element="_w6FugBK3EeWPr7pxbi20Rg" source="_nvQWoBK3EeWPr7pxbi20Rg" target="_w6A2ABK3EeWPr7pxbi20Rg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_j3GwFD79EeeFUpJtjfPkKQ" type="6001" element="_w6FugBK3EeWPr7pxbi20Rg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_j3GwFT79EeeFUpJtjfPkKQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_j3GwFj79EeeFUpJtjfPkKQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_w6G8ohK3EeWPr7pxbi20Rg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_emA-wNofEem3nK4z4KeV0A" type="4001" element="_el_woNofEem3nK4z4KeV0A" source="_yBZ9qhKsEeWPr7pxbi20Rg" target="_-99rkNohEem3nK4z4KeV0A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_emA-w9ofEem3nK4z4KeV0A" type="6001" element="_el_woNofEem3nK4z4KeV0A">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_emA-xNofEem3nK4z4KeV0A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_emA-wdofEem3nK4z4KeV0A" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_emA-wtofEem3nK4z4KeV0A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_emECENofEem3nK4z4KeV0A" id="(1.0,0.9666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_--JRwNohEem3nK4z4KeV0A" type="4001" element="_--IqsNohEem3nK4z4KeV0A" source="_-99rkNohEem3nK4z4KeV0A" target="_yBZ9wBKsEeWPr7pxbi20Rg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_--J40NohEem3nK4z4KeV0A" type="6001" element="_--IqsNohEem3nK4z4KeV0A">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_--J40dohEem3nK4z4KeV0A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_--JRwdohEem3nK4z4KeV0A" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_--JRwtohEem3nK4z4KeV0A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3Nu-kNojEem3nK4z4KeV0A" type="4003" element="_3NtwcNojEem3nK4z4KeV0A" source="_3NqtIdojEem3nK4z4KeV0A" target="_-99rkNohEem3nK4z4KeV0A">
      <styles xmi:type="notation:FontStyle" xmi:id="_3Nu-kdojEem3nK4z4KeV0A" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3Nu-ktojEem3nK4z4KeV0A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_9zOr4NojEem3nK4z4KeV0A" type="4003" element="_9zNdwNojEem3nK4z4KeV0A" source="_9zJzYNojEem3nK4z4KeV0A" target="_yBZ9wBKsEeWPr7pxbi20Rg">
      <styles xmi:type="notation:FontStyle" xmi:id="_9zOr4dojEem3nK4z4KeV0A" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_9zOr4tojEem3nK4z4KeV0A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OY8g8NokEem3nK4z4KeV0A" type="4003" element="_OY754NokEem3nK4z4KeV0A" source="_OY3ocNokEem3nK4z4KeV0A" target="_yBZ9wBKsEeWPr7pxbi20Rg">
      <styles xmi:type="notation:FontStyle" xmi:id="_OY8g8dokEem3nK4z4KeV0A" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OY8g8tokEem3nK4z4KeV0A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kxug0dokEem3nK4z4KeV0A" type="4003" element="_kxug0NokEem3nK4z4KeV0A" source="_kxsrodokEem3nK4z4KeV0A" target="_GwHcEBK3EeWPr7pxbi20Rg">
      <styles xmi:type="notation:FontStyle" xmi:id="_kxug0tokEem3nK4z4KeV0A" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kxug09okEem3nK4z4KeV0A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8up0ANokEem3nK4z4KeV0A" type="4003" element="_8upM8NokEem3nK4z4KeV0A" source="_8umwsdokEem3nK4z4KeV0A" target="_yBZ9rhKsEeWPr7pxbi20Rg">
      <styles xmi:type="notation:FontStyle" xmi:id="_8up0AdokEem3nK4z4KeV0A" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8up0AtokEem3nK4z4KeV0A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KO5s8NolEem3nK4z4KeV0A" type="4003" element="_KO5F4NolEem3nK4z4KeV0A" source="_KO2CkNolEem3nK4z4KeV0A" target="_yBZ9sRKsEeWPr7pxbi20Rg">
      <styles xmi:type="notation:FontStyle" xmi:id="_KO5s8dolEem3nK4z4KeV0A" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KO5s8tolEem3nK4z4KeV0A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NLVB0dolEem3nK4z4KeV0A" type="4003" element="_NLVB0NolEem3nK4z4KeV0A" source="_NLTzsdolEem3nK4z4KeV0A" target="_nvQWoBK3EeWPr7pxbi20Rg">
      <styles xmi:type="notation:FontStyle" xmi:id="_NLVB0tolEem3nK4z4KeV0A" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NLVB09olEem3nK4z4KeV0A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
